# Generated by Django 6.0.4 on 2026-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPasscode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("drinks", "Drinks"),
                            ("dessert", "Dessert"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("passcode", models.CharField(max_length=4, unique=True)),
            ],
        ),
    ]
