# Generated by Django 6.0.4 on 2026-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_staffpasscode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="total_spent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
