# Generated by Django 6.0.4 on 2026-06-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customer_total_spent_order_loyalty_awarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="food_rating",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="review",
            name="overall_rating",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="review",
            name="problem_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problem_reviews",
                to="core.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="service_rating",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="HelpAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_alerts",
                        to="core.order",
                    ),
                ),
            ],
        ),
    ]
