# Generated by Django 6.0.4 on 2026-06-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_review_rating_review_food_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
