# Generated by Django 6.0.4 on 2026-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_menuitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this item in the Today's Picks / special offers carousel.",
            ),
        ),
    ]
