# Generated by Django 6.0.4 on 2026-06-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_menuitem_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="server_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="table",
            name="server_name",
            field=models.CharField(
                blank=True,
                help_text="Waiter/serveur currently assigned to this table.",
                max_length=100,
            ),
        ),
    ]
