# Generated by Django 6.0.4 on 2026-06-25 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_server_name_table_server_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("passcode", models.CharField(max_length=4, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate instead of deleting so order history stays attributed.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="table",
            name="server_name",
            field=models.CharField(
                blank=True,
                help_text="Display snapshot of the assigned serveur's name; kept in sync with server.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.server",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="server",
            field=models.ForeignKey(
                blank=True,
                help_text="Serveur currently assigned to this table.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="core.server",
            ),
        ),
    ]
