# Generated by Django 6.0.4 on 2026-06-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_backfill_servers"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpalert",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_alerts",
                to="core.table",
            ),
        ),
        migrations.AlterField(
            model_name="helpalert",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_alerts",
                to="core.order",
            ),
        ),
    ]
