# Generated by Django 6.0.4 on 2026-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_helpalert_table_alter_helpalert_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpalert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("call", "Call serveur / help"),
                    ("cancel", "Cancellation request"),
                ],
                default="call",
                max_length=10,
            ),
        ),
    ]
