# Generated by Django 6.0.4 on 2026-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_helpalert_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("SERVED", "Served"),
                    ("CANCELED", "Canceled"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
