from django.urls import path
from .views import (
    MenuView, TableHubView, TableHelpAlertView, CustomerLookupView, OrderCreateView, OrderDetailView,
    StaffLoginView, StaffLogoutView, StaffOrderItemsView, StaffOrderItemAdvanceView,
    ServerLoginView, ServerLogoutView,
    ServeurDashboardView, ServeurOrderCreateView, ServeurServeItemView,
    ServeurHelpAlertResolveView,
    ReviewCreateView, OrderHelpAlertView, StaffHelpAlertResolveView, AdminStatsView,
    AdminMenuItemListCreateView, AdminMenuItemDetailView,
    AdminTableListCreateView, AdminTableDetailView, AdminServerListView,
)

urlpatterns = [
    path('menu/', MenuView.as_view()),
    path('table/', TableHubView.as_view()),
    path('table/help/', TableHelpAlertView.as_view()),
    path('customer/', CustomerLookupView.as_view()),
    path('orders/', OrderCreateView.as_view()),
    path('orders/<int:pk>/', OrderDetailView.as_view()),
    path('orders/<int:pk>/help/', OrderHelpAlertView.as_view()),
    path('staff/login/', StaffLoginView.as_view()),
    path('staff/logout/', StaffLogoutView.as_view()),
    path('staff/order-items/', StaffOrderItemsView.as_view()),
    path('staff/order-items/<int:pk>/', StaffOrderItemAdvanceView.as_view()),
    path('staff/help-alerts/<int:pk>/resolve/', StaffHelpAlertResolveView.as_view()),
    path('serveur/login/', ServerLoginView.as_view()),
    path('serveur/logout/', ServerLogoutView.as_view()),
    path('serveur/dashboard/', ServeurDashboardView.as_view()),
    path('serveur/orders/', ServeurOrderCreateView.as_view()),
    path('serveur/order-items/<int:pk>/serve/', ServeurServeItemView.as_view()),
    path('serveur/help-alerts/<int:pk>/resolve/', ServeurHelpAlertResolveView.as_view()),
    path('reviews/', ReviewCreateView.as_view()),
    path('admin/stats/', AdminStatsView.as_view()),
    path('admin/menu-items/', AdminMenuItemListCreateView.as_view()),
    path('admin/menu-items/<int:pk>/', AdminMenuItemDetailView.as_view()),
    path('admin/tables/', AdminTableListCreateView.as_view()),
    path('admin/tables/<int:pk>/', AdminTableDetailView.as_view()),
    path('admin/servers/', AdminServerListView.as_view()),
]
